server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daily_cs_db?serverTimezone=Asia/Seoul
    username: system
    password: 3916
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100
          dialect: org.hibernate.dialect.MySQL8Dialect

  application.name: splearn
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  
  # Spring AI 설정
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
